---
language: ruby
notifications:
  email: false
branches:
  only:
  - master
os: osx
osx_image:
- xcode8.2
- xcode8
env:
- FORMULA=leptonica@169
- FORMULA=pandoc@1131
- FORMULA=nu@0
- FORMULA=isl@011
- FORMULA=mongodb@32
- FORMULA=libmongoclient@legacy
- FORMULA=varnish@4
- FORMULA=glfw@2
- FORMULA=postgresql@8
- FORMULA=libotr@4
- FORMULA=ruby@20
- FORMULA=hadoop@0202
- FORMULA=bazel@02
- FORMULA=elasticsearch@20
- FORMULA=zeromq@32
- FORMULA=cassandra@20
- FORMULA=go@14
- FORMULA=openjpeg@20
- FORMULA=grails@24
- FORMULA=node@010
- FORMULA=kubernetes-cli@13
- FORMULA=node@4-lts
- FORMULA=valgrind@38
- FORMULA=drush@5
- FORMULA=play@13
- FORMULA=llvm-gcc@28
- FORMULA=node@4
- FORMULA=libuv@0
- FORMULA=log4cplus@10
- FORMULA=ansible@14
- FORMULA=jpeg@6b
- FORMULA=doxygen@1831
- FORMULA=cmake@28
- FORMULA=cloog@018
- FORMULA=redis@26
- FORMULA=isl@014
- FORMULA=llvm@32
- FORMULA=cloog-ppl@015
- FORMULA=plowshare@3
- FORMULA=kettle@54
- FORMULA=jruby@1721
- FORMULA=gst-plugins-good@010
- FORMULA=gcc@44
- FORMULA=libxc@21
- FORMULA=bind@99
- FORMULA=protobuf@260
- FORMULA=openssl@098
- FORMULA=android-ndk@r12b
- FORMULA=node@08
- FORMULA=ledger@26
- FORMULA=apache-spark@121
- FORMULA=gdal@111
- FORMULA=elasticsearch@24
- FORMULA=appledoc@22
- FORMULA=llvm@36
- FORMULA=elasticsearch@0.20
- FORMULA=zeromq@22
- FORMULA=cmake@30
- FORMULA=spidermonkey@180
- FORMULA=ruby@182
- FORMULA=logstash@22
- FORMULA=jetty@8
- FORMULA=jenkins@lts
- FORMULA=erlang@r19
- FORMULA=jruby@9000
- FORMULA=postgis@20
- FORMULA=gradle@27
- FORMULA=elasticsearch@12
- FORMULA=perl@516
- FORMULA=gcc@47
- FORMULA=virtuoso@616
- FORMULA=gst-python@010
- FORMULA=unison@232
- FORMULA=rebar@3
- FORMULA=gradle@110
- FORMULA=grails@25
- FORMULA=srtp@15
- FORMULA=ruby@192
- FORMULA=gawk@3
- FORMULA=cassandra@21
- FORMULA=gradle@221
- FORMULA=appledoc@20
- FORMULA=jpeg@9
- FORMULA=erlang@r15
- FORMULA=gradle@24
- FORMULA=python@32
- FORMULA=mongodb@30
- FORMULA=mapnik@2
- FORMULA=solr@36
- FORMULA=nasm@21106
- FORMULA=cassandra@0.6
- FORMULA=jetty@76
- FORMULA=protobuf@250
- FORMULA=mongodb@26
- FORMULA=libgee@08
- FORMULA=scala@210
- FORMULA=guile@18
- FORMULA=boot2docker@133
- FORMULA=libdvdcss@12
- FORMULA=boost@155
- FORMULA=hdf@4
- FORMULA=postgresql@93
- FORMULA=grails@224
- FORMULA=perl@514
- FORMULA=tomcat@6
- FORMULA=ruby@193
- FORMULA=clojure@14
- FORMULA=docker@162
- FORMULA=nettle@3
- FORMULA=solr@14
- FORMULA=cvsps@2
- FORMULA=erlang@r14
- FORMULA=solr@55
- FORMULA=open-mpi@16
- FORMULA=go@13
- FORMULA=autoconf@264
- FORMULA=gcc@5
- FORMULA=grails@223
- FORMULA=unison@240
- FORMULA=elasticsearch@17
- FORMULA=objective-caml@312
- FORMULA=kafka@090
- FORMULA=libcouchbase@1
- FORMULA=postgis@15
- FORMULA=maven@2
- FORMULA=ruby@187
- FORMULA=erlang@r16
- FORMULA=jboss-as@5
- FORMULA=imagemagick-ruby@186
- FORMULA=postgresql@95
- FORMULA=mysql@55
- FORMULA=android-ndk@r10c
- FORMULA=libxml@278
- FORMULA=apache-spark@16
- FORMULA=mkvtoolnix@58
- FORMULA=gsl@114
- FORMULA=docker@133
- FORMULA=python@24
- FORMULA=erlang@r17
- FORMULA=scala@29
- FORMULA=llvm@38
- FORMULA=gcc@6
- FORMULA=python@26
- FORMULA=go@16
- FORMULA=boot2docker@162
- FORMULA=hive@011
- FORMULA=coq@83
- FORMULA=phantomjs@198
- FORMULA=vtk@5
- FORMULA=tomcat@7
- FORMULA=redis@28
- FORMULA=apache-spark@131
- FORMULA=protobuf@241
- FORMULA=mariadb@10
- FORMULA=grails@22
- FORMULA=kubernetes-cli@14
- FORMULA=android-ndk@r9d
- FORMULA=grails@20
- FORMULA=libmpc@08
- FORMULA=python@31
- FORMULA=grails@31
- FORMULA=postgresql@91
- FORMULA=perl@518
- FORMULA=nifi@021
- FORMULA=logstash@21
- FORMULA=hadoop@25
- FORMULA=zeromq@40
- FORMULA=kibana@44
- FORMULA=phantomjs@182
- FORMULA=gecode@373
- FORMULA=ppl@011
- FORMULA=gradle@16
- FORMULA=subversion@16
- FORMULA=mysql@56
- FORMULA=selenium-server-standalone@245
- FORMULA=elasticsearch@14
- FORMULA=v8@315
- FORMULA=gstreamer@010
- FORMULA=thrift@090
- FORMULA=allegro@4
- FORMULA=gnuplot@4
- FORMULA=subversion@18
- FORMULA=boot2docker@141
- FORMULA=appledoc@21
- FORMULA=bash-completion@2
- FORMULA=astyle@204
- FORMULA=grails@13
- FORMULA=mono@3
- FORMULA=libpqxx@3
- FORMULA=openjpeg@21
- FORMULA=maven@31
- FORMULA=camlp5@606
- FORMULA=play@22
- FORMULA=gcc@43
- FORMULA=boost-python@159
- FORMULA=gst-plugins-base@010
- FORMULA=play@12
- FORMULA=gnupg@2
- FORMULA=lua@52
- FORMULA=libidn@2
- FORMULA=ansible@20
- FORMULA=mongodb@24
- FORMULA=gmp@4
- FORMULA=libpng@12
- FORMULA=erlang@r18
- FORMULA=rabbitmq@30
- FORMULA=gnutls@34
- FORMULA=elasticsearch@13
- FORMULA=berkeley-db@4
- FORMULA=gradle@18
- FORMULA=swig@2
- FORMULA=sonar@4
- FORMULA=android-ndk@r11c
- FORMULA=jython@253
- FORMULA=elasticsearch@21
- FORMULA=bison@27
- FORMULA=ffmpeg@28
- FORMULA=gst-plugins-bad@010
- FORMULA=llvm@35
- FORMULA=gsl@1
- FORMULA=gradle@21
- FORMULA=glfw@3
- FORMULA=percona-server@55
- FORMULA=boost@150
- FORMULA=llvm@31
- FORMULA=gst-ffmpeg@010
- FORMULA=android-ndk@r10d
- FORMULA=raptor@1
- FORMULA=jboss-forge@1
- FORMULA=valgrind@36
- FORMULA=docker@141
- FORMULA=antlr@2
- FORMULA=freetds@091
- FORMULA=postgresql@94
- FORMULA=docker@150
- FORMULA=gradle@28
- FORMULA=go@15
- FORMULA=elasticsearch@23
- FORMULA=kafka@080
- FORMULA=gcc@46
- FORMULA=clang-format@38
- FORMULA=ruby@186
- FORMULA=riak@132
- FORMULA=ansible@18
- FORMULA=syncthing@010
- FORMULA=influxdb@08
- FORMULA=play@14
- FORMULA=node@012
- FORMULA=mariadb@100
- FORMULA=docker@111
- FORMULA=node@04
- FORMULA=antlr@3
- FORMULA=grails@23
- FORMULA=qt@55
- FORMULA=cassandra@22
- FORMULA=gradle@26
- FORMULA=jruby@168
- FORMULA=logstash@23
- FORMULA=duplicity@06
- FORMULA=gnupg@21
- FORMULA=hive@010
- FORMULA=phantomjs@17
- FORMULA=boost@159
- FORMULA=saxon@6
- FORMULA=solr@4
- FORMULA=llvm@33
- FORMULA=mapnik@071
- FORMULA=mysql@51
- FORMULA=gst-plugins-ugly@010
- FORMULA=gnutls@3
- FORMULA=swig@304
- FORMULA=apache-spark@141
- FORMULA=python@25
- FORMULA=boost@149
- FORMULA=postgresql@9
- FORMULA=go@12
- FORMULA=android-ndk@r10e
- FORMULA=gcc@49
- FORMULA=eigen@2
- FORMULA=elasticsearch@22
- FORMULA=povray@36
- FORMULA=subversion@17
- FORMULA=kibana@43
- FORMULA=logstash@24
- FORMULA=maven@32
- FORMULA=hadoop@121
- FORMULA=lua@53
- FORMULA=kibana@41
- FORMULA=gradle@214
- FORMULA=grails@21
- FORMULA=autoconf@213
- FORMULA=gegl@02
- FORMULA=isl@012
- FORMULA=vim@74
- FORMULA=mpfr@2
- FORMULA=phantomjs@192
- FORMULA=zeromq@405
- FORMULA=json-c@010
- FORMULA=protobuf@240a
- FORMULA=arangodb@2
- FORMULA=zeromq@3
- FORMULA=elasticsearch@11
- FORMULA=maven@30
- FORMULA=scala@211
- FORMULA=lua@51
- FORMULA=grails@137
- FORMULA=git-tf@2.0.2
- FORMULA=apache-spark@15
- FORMULA=hadoop@252
- FORMULA=openssl@101
- FORMULA=llvm@34
- FORMULA=lz4r@117
- FORMULA=giflib@5
- FORMULA=redis@1310
- FORMULA=squid@2
- FORMULA=ppl@10
- FORMULA=node@5
- FORMULA=node@06
- FORMULA=solr@54
- FORMULA=gcc@45
- FORMULA=gradle@20
- FORMULA=ruby@22
- FORMULA=percona-server@56
- FORMULA=gradle@112
- FORMULA=cmake@31
- FORMULA=hive@12
- FORMULA=kibana@42
- FORMULA=ansible@19
- FORMULA=docker@110
- FORMULA=ruby@21
- FORMULA=eigen@32
- FORMULA=cassandra@10
- FORMULA=llvm@37
- FORMULA=docker@171
- FORMULA=elasticsearch@090
- FORMULA=boost@160
- FORMULA=pandoc-citeproc@05
- FORMULA=spidermonkey@45
- FORMULA=gst-rtsp@010
- FORMULA=qt@52
- FORMULA=erlang@r13
- FORMULA=automake@112
- FORMULA=cassandra@12
- FORMULA=redis@24
- FORMULA=drush@4
- FORMULA=node@6-lts
- FORMULA=varnish@3
- FORMULA=postgresql@92
- FORMULA=gcc@48
- FORMULA=allegro@5
- FORMULA=openssl@100
script:
- ruby scripts/build_formula.rb $FORMULA
